### ISSUE TITLE
💡[Feature] 로컬에서 이미지를 다운받아 byte형식에서 string 형식으로 변형하는 예시 적용

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#100]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 로컬에서 이미지를 다운받아 byte형식에서 string 형식으로 변형하는 예시 적용

## 📝 기능 상세 내용

- 로컬에서 이미지를 다운받아 byte형식에서 string 형식으로 변형하는 예시 적용

## ✅ TODO

- [x] 로컬에서 이미지를 다운받아 byte형식에서 string 형식으로 변형하는 예시 적용
