### ISSUE TITLE
💡[Feature] 로컬에서 이미지를 업로드 구현 및 내 기록 생성과 수정에 적용

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#102]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 로컬에서 이미지를 업로드 구현 및 내 기록 생성과 수정에 적용

## 📝 기능 상세 내용

- 로컬에서 이미지를 업로드 구현 및 내 기록 생성과 수정에 적용

## ✅ TODO

- [x] 로컬에서 이미지를 업로드 구현 및 내 기록 생성과 수정에 적용
