### ISSUE TITLE
💡[Feature] 캘린더와 전시회 좋아요 api 이미지 다운로드 코드 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#112]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 캘린더와 전시회 좋아요 api 이미지 다운로드 코드 추가

## 📝 기능 상세 내용

- 캘린더와 전시회 좋아요 api 이미지 다운로드 코드 추가

## ✅ TODO

- [x] 캘린더와 전시회 좋아요 api 이미지 다운로드 코드 추가
