### ISSUE TITLE
🔨[Refactor] api 요청 데이터 중 사진 데이터 생성과 수정의 null 허용 유무 구분

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#119]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- api 요청 데이터 중 사진 데이터 생성과 수정의 null 허용 유무 구분

## 📝 리팩토링 상세 내용

- 생성 관련 api 요청 데이터 중 사진 데이터는 null 허용하지 않도록 함.
    - 사용자가 사진을 선택하면 선택한 사진 업로드
    - 그렇지 않으면 프론트가 가지고 있는 디폴트 사진으로 업로드
- 수정 관련 api 요청 데이터 중 사진 데이터는 null 허용함.
    - 사용자가 사진을 선택하면 선택한 사진 업로드
    - 사용자가 디폴트 사진으로 선택하면 프론트가 가지고 있는 디폴트 사진으로 업로드
    - null 데이터를 가지고 요청을 하면 기존 사진을 유지하는 것으로 인식

## ✅ TODO

- [x] api 요청 데이터 중 사진 데이터 생성과 수정의 null 허용 유무 구분
