### ISSUE TITLE
💡[Feature] 닉네임 중복 확인

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Backend#122]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 닉네임 중복 확인

## 📝 기능 상세 내용

- 닉네임 중복 확인
- 
## ✅ TODO

- [x] 닉네임 중복 확인
