### ISSUE TITLE
🔨[Refactor] 탈퇴 회원의 기록 및 기록의 공개 여부 고려

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#126]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 탈퇴 회원의 기록 및 기록의 공개 여부 고려

## 📝 리팩토링 상세 내용

- 탈퇴 후 기록 조회 중 사용자 아이디가 -1인 경우 고려하여 코드 수정
- 기록 공개 여부에 따라 전시회 상세 정보 중 리뷰에 해당되는 기록과 모임 내의 기록, 전시 메이트의 기록이 다르게 보여지도록 코드 수정
## ✅ TODO

- [x] 탈퇴 회원의 기록 고려
- [x] 기록의 공개 여부 고려
