### ISSUE TITLE
💡[Feature] 예외 처리 코드 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#13]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 예외 처리 코드 추가

## 📝 기능 상세 내용

- 예외 처리 코드 추가

## ✅ TODO

- [x] 예외 처리 코드 추가
