### ISSUE TITLE
💡[Feature] 간단한 프론트엔드 연결 코드

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#130]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 간단한 프론트엔드 연결 코드

## 📝 기능 상세 내용

- 간단한 프론트엔드 연결 코드

## ✅ TODO

- [x] 간단한 프론트엔드 연결 코드
