### ISSUE TITLE
🔨[Refactor] 기록 수정 중 방문 날짜 수정 적용

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#134]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 기록 수정 중 방문 날짜 수정 적용

## 📝 리팩토링 상세 내용

- 기록 수정 중 방문 날짜 수정 적용

## ✅ TODO

- [x] 기록 수정 중 방문 날짜 수정 적용
