### ISSUE TITLE
🔨[Refactor] 내 기록이 있는 전시회 리스트 조회에 querydsl 사용

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#136]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 내 기록이 있는 전시회 리스트 조회에 querydsl 사용

## 📝 리팩토링 상세 내용

- 내 기록이 있는 전시회 리스트 조회에 querydsl 사용

## ✅ TODO

- [x] 내 기록이 있는 전시회 리스트 조회에 querydsl 사용
