### ISSUE TITLE
🔨[Refactor] 사용자 정보 조회 응답에 알림 데이터 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#138]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 사용자 정보 조회 응답에 알림 데이터 추가

## 📝 리팩토링 상세 내용

- 사용자 정보 조회 응답에 알림 데이터 추가

## ✅ TODO

- [x] 사용자 정보 조회 응답에 알림 데이터 추가
