### ISSUE TITLE
🔨[Refactor] userexh 위치 이동

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#142]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- userexh 위치 이동

## 📝 리팩토링 상세 내용

- userexh 위치 이동
## ✅ TODO

- [x] userexh 위치 이동
