### ISSUE TITLE
💡[Feature] 특정 날짜에 방문한 전시회에 대한 기록 목록 조회 api 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#144]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 특정 날짜에 방문한 전시회에 대한 기록 목록 조회 api 구현

## 📝 기능 상세 내용

- 특정 날짜에 방문한 전시회에 대한 기록 목록 조회 api 구현

## ✅ TODO

- [x] 특정 날짜에 방문한 전시회에 대한 기록 목록 조회 api 구현
