### ISSUE TITLE
🔨[Refactor] mate 패키지 이름을 mates로 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#146]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- mate 패키지 이름을 mates로 변경

## 📝 리팩토링 상세 내용

- mate 패키지 이름을 mates로 변경

## ✅ TODO

- [x] mate 패키지 이름을 mates로 변경
