### ISSUE TITLE
🔨[Refactor] gatheringExhId를 gatherExhId로 통일

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#147]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- gatheringExhId를 gatherExhId로 통일

## 📝 리팩토링 상세 내용

- 모임과 관련된 단어가 gather로 시작하기 때문에 gatheringExhId도 gatherExhId로 바꿔 통일성 유지

## ✅ TODO

- [x] gatheringExhId를 gatherExhId로 통일
