### ISSUE TITLE
🔨[Refactor] 특정 날짜에 방문한 전시회에 대한 기록 목록 조회 중 gatherExhId를 gatherId로 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#148]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 특정 날짜에 방문한 전시회에 대한 기록 목록 조회 중 gatherExhId를 gatherId로 변경

## 📝 리팩토링 상세 내용

- 앱에서 화면 이동 중 캘린더 화면의 전시회에 대해서 가지고 있는 정보가 gatherExhId가 아닌 gatherId이므로 gatherExhId를 gatherId로 변경

## ✅ TODO

- [x] 특정 날짜에 방문한 전시회에 대한 기록 목록 조회 중 gatherExhId를 gatherId로 변경
