### ISSUE TITLE
💡[Feature] 한 전시회에 대해 캘린더에 저장된 날짜 조회 기능 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#15]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 한 전시회에 대해 캘린더에 저장된 날짜 조회 기능 구현

## 📝 기능 상세 내용

- 한 전시회에 대해 캘린더에 저장된 날짜 조회 기능 구현
- UserExh 테이블 추가
- 로직 구현

## ✅ TODO

- [x] UserExh 테이블 추가
- [x] 한 전시회에 대한 캘린더에 저장된 개인의 일정 날짜 조회 로직 구현
- [x] 한 전시회에 대한 캘린더에 저장된 특정 모임의 일정 날짜 조회 로직 구현
