### ISSUE TITLE
🔨[Refactor] 프론트에서 캘린더의 날짜 선택하여 기록 요청 시 필요한 데이터 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#152]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 프론트에서 캘린더의 날짜 선택하여 기록 요청 시 필요한 데이터 추가

## 📝 리팩토링 상세 내용

- 프론트에서 캘린더의 날짜 선택하여 기록 요청 시 필요한 데이터 추가

## ✅ TODO

- [x] 프론트에서 캘린더의 날짜 선택하여 기록 요청 시 필요한 데이터 추가
