### ISSUE TITLE
🔨[Refactor] 전시회 검색 조회 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#154]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 전시회 검색 조회 수정

## 📝 리팩토링 상세 내용

- 전시회 검색 조회 시 검색 내용, 카테고리 등 여러 가지 조합으로 검색이 가능하도록 수정

## ✅ TODO

- [x] 전시회 검색 조회 수정
