### ISSUE TITLE
🔨[Refactor] 전시회 여러가지 검색 조회 가능하도록 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#157]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 전시회 여러가지 검색 조회 가능하도록 수정

## 📝 리팩토링 상세 내용

- 전시회 여러가지 검색 조회 가능하도록 수정

## ✅ TODO

- [x] 전시회 여러가지 검색 조회 가능하도록 수정
