### ISSUE TITLE
🔨[Refactor] 전시 메이트의 공개된 기록이 있는 전시회 목록 데이터 요청 시 querydsl 사용으로 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#160]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 전시 메이트의 공개된 기록이 있는 전시회 목록 데이터 요청 시 querydsl 사용으로 변경
## 📝 리팩토링 상세 내용

- 전시 메이트의 공개된 기록이 있는 전시회 목록 데이터 요청 시 querydsl 사용으로 변경
## ✅ TODO

- [x] 전시 메이트의 공개된 기록이 있는 전시회 목록 데이터 요청 시 querydsl 사용으로 변경
