### ISSUE TITLE
🔨[Refactor] 사용자 로그인 시 사용자 정보 초기화를 고려한 로그인 요청 데이터 간소화

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#162]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 사용자 로그인 시 사용자 정보 초기화를 고려한 로그인 요청 데이터 간소화

## 📝 리팩토링 상세 내용

- 사용자 로그인 시 사용자 정보 초기화를 고려한 로그인 요청 데이터 간소화
## ✅ TODO

- [x] 사용자 로그인 시 사용자 정보 초기화를 고려한 로그인 요청 데이터 간소화
