### ISSUE TITLE
🔨[Refactor] 사용자의 정보 초기화 여부에 따른 로그인 요청에 대한 응답 데이터 구분

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#164]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 사용자의 정보 초기화 여부에 따른 로그인 요청에 대한 응답 데이터 구분

## 📝 리팩토링 상세 내용

- 사용자의 정보 초기화 여부에 따른 로그인 요청에 대한 응답 데이터 구분
## ✅ TODO

- [x] 사용자의 정보 초기화 여부에 따른 로그인 요청에 대한 응답 데이터 구분
