### ISSUE TITLE
🔨[Refactor] 다이어리 목록 반환 데이터에 userId 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#166]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 다이어리 목록 반환 데이터에 userId 추가

## 📝 리팩토링 상세 내용

- 다이어리 목록 반환 데이터에 userId 추가

## ✅ TODO

- [x] 다이어리 목록 반환 데이터에 userId 추가
