### ISSUE TITLE
🐞[Bug] 모임에서 나간 사용자의 닉네임 안 보이도록 수정 및 모임의 공개된 기록에 대해서만 평점 구하도록 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#168]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 모임에서 나간 사용자의 닉네임 안 보이도록 수정 및 모임의 공개된 기록에 대해서만 평점 구하도록 수정

## 🐛 버그 상세 내용

- 모임에서 나간 사용자의 닉네임 안 보이도록 수정
- 모임의 공개된 기록에 대해서만 평점 구하도록 수정

## ✅ TODO

- [x] 모임에서 나간 사용자의 닉네임 안 보이도록 수정
- [x] 모임의 공개된 기록에 대해서만 평점 구하도록 수정
