### ISSUE TITLE
🐞[Bug] 전시회 기록 목록 조회 중 사용자 정보 조회에서 발생하는 404 에러 처리

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#170]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 전시회 기록 목록 조회 중 사용자 정보 조회에서 발생하는 404 에러 처리

## 🐛 버그 상세 내용

- 전시회 기록 목록 조회 중 사용자 정보 조회에서 발생하는 404 에러 처리

## ✅ TODO

- [x] 전시회 기록 목록 조회 중 사용자 정보 조회에서 발생하는 404 에러 처리
