### ISSUE TITLE
🔨[Refactor] 동일한 이메일을 가진 소셜 로그인 통합 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#182]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 동일한 이메일을 가진 소셜 로그인 통합 구현

## 📝 리팩토링 상세 내용

- 새로운 소셜 로그인으로 시도할 때, 동일한 이메일이 존재하는지 확인
- 동일한 이메일이 있을 경우, 사용자의 계정 통합 여부에 따라 로직 구분
    - 추가적인 api 필요(= 계정 통합 여부에 따라 api 생성)
    - 통합하겠다고 하면, 통합 로직 실행
    - 통합하지 않겠다고 하면, 새로운 계정 생성 로직 실행
- 동일한 이메일이 없을 경우, 새로운 계정 생성

## ✅ TODO

- [x] 동일한 이메일을 가진 소셜 로그인 통합 구현
