### ISSUE TITLE
🐞[Bug] 전시회 리뷰 썸네일 반환 데이터 오류

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#190]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 전시회 리뷰 썸네일 반환 데이터 오류

## 🐛 버그 상세 내용

- 전시회 리뷰 썸네일 반환 데이터 오류

## ✅ TODO

- [x] 전시회 리뷰 썸네일 반환 데이터 오류
