### ISSUE TITLE
💡[Feature] 방문 엔티티와 기록 엔트트 새로 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#195]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 방문 엔티티와 기록 엔트트 새로 추가

## 📝 기능 상세 내용

- 방문 엔티티와 기록 엔트트 새로 추가

## ✅ TODO

- [x] 방문 엔티티와 기록 엔트트 새로 추가
