### ISSUE TITLE
🔨[Refactor] myexh 파트에 새로운 전시방문 및 기록 엔티티 적용

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#197]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- myexh 파트에 새로운 전시방문 및 기록 엔티티 적용

## 📝 리팩토링 상세 내용

- myexh 파트에 새로운 전시방문 및 기록 엔티티 적용

## ✅ TODO

- [x] myexh 파트에 새로운 전시방문 및 기록 엔티티 적용
