### ISSUE TITLE
💡[Feature] 풀 리퀘스트 템플릿 생성

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#2]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 풀 리퀘스트 템플릿 생성

## 📝 기능 상세 내용

- 풀 리퀘스트 템플릿 작성

## ✅ TODO

- [x] 풀 리퀘스트 템플릿 작성
