### ISSUE TITLE
🔨[Refactor] 점을 포함한 날짜 형식으로 바꾸기

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#214]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 점을 포함한 날짜 형식으로 바꾸기

## 📝 리팩토링 상세 내용

- 점을 포함한 날짜 형식으로 바꾸기
## ✅ TODO

- [x] 점을 포함한 날짜 형식으로 바꾸기
