### ISSUE TITLE
🔨[Refactor] 로컬 대신 aws s3에 사진 업로드로 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#216]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 로컬 대신 aws s3에 사진 업로드로 변경

## 📝 리팩토링 상세 내용

- 로컬 대신 aws s3에 사진 업로드로 변경

## ✅ TODO

- [x] 로컬 대신 aws s3에 사진 업로드로 변경
