### ISSUE TITLE
🔨[Refactor] 기록 내용에 첨부된 사진 저장

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#218]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 기록 내용에 첨부된 사진 저장

## 📝 리팩토링 상세 내용

- 기록 내용에 첨부된 사진을 aws s3에 저장하고 내용 중 사진 정보를 aws s3 url로 대체.
- aws s3 저장 전 해당 기록의 기존 사진들 모두 삭제 후 저장.

## ✅ TODO

- [x] 기록 내용에 첨부된 사진 저장
