### ISSUE TITLE
💡[Feature] 전시 메이트와 모임 관련 페이지 새로고침 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#219]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 전시 메이트와 모임 관련 페이지 새로고침 추가
## 📝 기능 상세 내용

- 전시 메이트와 모임 관련 페이지 새로고침 추가

## ✅ TODO

- [ ] 전시 메이트와 모임 관련 페이지 새로고침 추가
