### ISSUE TITLE
💡[Feature] 등록할 전시회 목록 조회(사용자/관리자)

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#226]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 등록할 전시회 목록 조회(사용자/관리자)

## 📝 기능 상세 내용

- 등록할 전시회 목록 조회(사용자/관리자)

## ✅ TODO

- [x] 등록할 전시회 목록 조회(사용자/관리자)
