### ISSUE TITLE
💡[Feature] 전시회 등록 요청 확인 코멘트 추가 및 전시회 정보 수정 (관리자)

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#228]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 전시회 등록 요청 확인 코멘트 추가 및 전시회 정보 수정 (관리자)

## 📝 기능 상세 내용

- 전시회 등록 요청 확인 코멘트 추가 및 전시회 정보 수정 (관리자)

## ✅ TODO

- [x] 전시회 등록 요청 확인 코멘트 추가 및 전시회 정보 수정 (관리자)
