### ISSUE TITLE
🔨[Refactor] user 코딩 컨벤션 적용

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#23]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- user 코딩 컨벤션 적용

## 📝 리팩토링 상세 내용

- user 코딩 컨벤션 적용

## ✅ TODO

- [x] user 코딩 컨벤션 적용
