### ISSUE TITLE
🔨[Refactor] 사용자가 등록한 전시회를 포함한 전시회 리스트 반환 순서 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#238]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 사용자가 등록한 전시회를 포함한 전시회 리스트 반환 순서 추가

## 📝 리팩토링 상세 내용

- 사용자가 등록한 전시회를 포함한 전시회 리스트 조회 추가
- 전시회 리스트 반환 순서 추가

## ✅ TODO

- [ ] 사용자가 등록한 전시회를 포함한 전시회 리스트 조회 추가
- [ ] 전시회 리스트 반환 순서 추가
