### ISSUE TITLE
🐞[Bug] 전시회 등록 요청 데이터 중 포스터 데이터 타입 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#241]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 전시회 등록 요청 데이터 중 포스터 데이터 타입 변경

## 🐛 버그 상세 내용

- 전시회 등록 요청 데이터 중 포스터 데이터 타입 변경

## ✅ TODO

- [x] 전시회 등록 요청 데이터 중 포스터 데이터 타입 변경
