### ISSUE TITLE
🔨[Refactor] 관리자의 등록 전시회 조회 적용 추가 및 등록 전시회 업데이트 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#243]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 관리자의 등록 전시회 조회 적용 추가 및 등록 전시회 업데이트 수정

## 📝 리팩토링 상세 내용

- 관리자의 등록 전시회 조회 적용 추가 및 등록 전시회 업데이트 수정

## ✅ TODO

- [x] 관리자의 등록 전시회 조회 적용 추가 및 등록 전시회 업데이트 수정
