### ISSUE TITLE
🔨[Refactor] 관리자 요청일 경우 관리자인지 확인 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#245]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 관리자 요청일 경우 관리자인지 확인 추가

## 📝 리팩토링 상세 내용

- 관리자 요청일 경우 관리자인지 확인 추가

## ✅ TODO

- [x] 관리자 요청일 경우 관리자인지 확인 추가
