### ISSUE TITLE
🔨[Refactor] 기록 최초 작성 날짜 역순 정렬로 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#249]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 기록 최초 작성 날짜 역순 정렬로 수정

## 📝 리팩토링 상세 내용

- 기록 최초 작성 날짜 역순 정렬로 수정

## ✅ TODO

- [x] 기록 최초 작성 날짜 역순 정렬로 수정
