### ISSUE TITLE
💡[Feature] gathering 기본 파일 생성

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#25]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- gathering 기본 파일 생성

## 📝 기능 상세 내용

- gathering 기본 파일 생성

## ✅ TODO

- [x] gathering 기본 파일 생성
