### ISSUE TITLE
🔨[Refactor] 개인 방문 정보를 디폴트로 반환으로 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#251]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 개인 방문 정보를 디폴트로 반환으로 수정

## 📝 리팩토링 상세 내용

- 개인 방문 정보를 디폴트로 반환으로 수정

## ✅ TODO

- [x] 개인 방문 정보를 디폴트로 반환으로 수정
