### ISSUE TITLE
💡[Feature] 검색어로 전시회 조회 api

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Backend#253]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 검색어로 전시회 조회 api

## 📝 기능 상세 내용

- “/exhibitions/search” request data: searchName

## ✅ TODO

- [ ] 검색어로 전시회 조회 api 생성
