### ISSUE TITLE
🔨[Refactor] 전시회 리뷰 최신순으로 정렬

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#257]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 전시회 리뷰 최신순으로 정렬

## 📝 리팩토링 상세 내용

- 전시회 리뷰 최신순으로 정렬

## ✅ TODO

- [x] 전시회 리뷰 최신순으로 정렬
