### ISSUE TITLE
🔨[Refactor] 모임의 방문 날짜 정보에 모임 정보 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#264]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 모임의 방문 날짜 정보에 모임 정보 추가

## 📝 리팩토링 상세 내용

- 모임의 방문 날짜 정보에 모임 정보 추가

## ✅ TODO

- [x] 모임의 방문 날짜 정보에 모임 정보 추가
