### ISSUE TITLE
🐞[Bug] 전시회 리뷰 중 탈퇴 사용자의 전시회 모임 정보 없는 것 해결

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#266]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 전시회 리뷰 중 탈퇴 사용자의 전시회 모임 정보 없는 것 해결

## 🐛 버그 상세 내용

- 전시회 리뷰 중 탈퇴 사용자의 전시회 모임 정보 없는 것 해결

## ✅ TODO

- [x] 전시회 리뷰 중 탈퇴 사용자의 전시회 모임 정보 없는 것 해결
