### ISSUE TITLE
💡[Feature] 모임 목록 조회

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Backend#27]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 모임 목록 조회

## 📝 기능 상세 내용

- 모임 목록 조회

## ✅ TODO

- [x] 모임 목록 조회
