### ISSUE TITLE
🔨[Refactor] 모임 목록을 사용자가 모임에서 최근에 전시회를 방문한 날짜 순 정렬로 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#270]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 모임 목록을 사용자가 모임에서 최근에 전시회를 방문한 날짜 순 정렬로 수정

## 📝 리팩토링 상세 내용

- 모임 목록을 사용자가 모임에서 최근에 전시회를 방문한 날짜 순 정렬로 수정

## ✅ TODO

- [x] 모임 목록을 사용자가 모임에서 최근에 전시회를 방문한 날짜 순 정렬로 수정
