### ISSUE TITLE
🔨[Refactor] 전시 메이트 검색 시 메이트가 아닌 유저 리스트와 이미 친구인 유저 리스트로 반환하고 닉네임 순으로 정렬로 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#272]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 전시 메이트 검색 시 메이트가 아닌 유저 리스트와 이미 친구인 유저 리스트로 반환하고 닉네임 순으로 정렬로 변경

## 📝 리팩토링 상세 내용

- 전시 메이트 검색 시 메이트가 아닌 유저 리스트와 이미 친구인 유저 리스트로 반환하고 닉네임 순으로 정렬로 변경

## ✅ TODO

- [x] 전시 메이트 검색 시 메이트가 아닌 유저 리스트와 이미 친구인 유저 리스트로 반환하고 닉네임 순으로 정렬로 변경
