### ISSUE TITLE
🔨[Refactor] 모임 메이트 검색 시 새로 추가할 유저 리스트와 이미 포함된 유저 리스트로 반환하고 닉네임 순으로 정렬로 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#275]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 모임 메이트 검색 시 새로 추가할 유저 리스트와 이미 포함된 유저 리스트로 반환하고 닉네임 순으로 정렬로 변경

## 📝 리팩토링 상세 내용

- 모임 메이트 검색 시 새로 추가할 유저 리스트와 이미 포함된 유저 리스트로 반환하고 닉네임 순으로 정렬로 변경

## ✅ TODO

- [ ] 모임 메이트 검색 시 새로 추가할 유저 리스트와 이미 포함된 유저 리스트로 반환하고 닉네임 순으로 정렬로 변경
