### ISSUE TITLE
💡[Feature] 외부 서버 터널링

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#278]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 외부 서버 터널링

## 📝 기능 상세 내용

- 외부 서버 터널링

## ✅ TODO

- [x] 외부 서버 터널링
