### ISSUE TITLE
💡[Feature] 모임 생성 기능 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#28]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 모임 생성 기능 구현

## 📝 기능 상세 내용

- 모임 생성 기능 구현

## ✅ TODO

- [x] 모임 생성 기능 구현
