### ISSUE TITLE
🔨[Refactor] 사진 데이터가 널인 경우 반영

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#284]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 사진 데이터가 널인 경우 반영

## 📝 리팩토링 상세 내용

- 사진 데이터가 널인 경우 반영

## ✅ TODO

- [x] 사진 데이터가 널인 경우 반영
