### ISSUE TITLE
🔨[Refactor] 등록 현황을 3가지로 분리해서 반영

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#285]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 등록 현황을 3가지로 분리해서 반영

## 📝 리팩토링 상세 내용

- 등록 현황을 3가지로 분리해서 반영

## ✅ TODO

- [x] 등록 현황을 3가지로 분리해서 반영
