### ISSUE TITLE
🔨[Refactor] 사용자의 등록 전시회 목록을 등록 현황에 우선순위를 두고 최신순으로 정렬

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#286]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 사용자의 등록 전시회 목록을 등록 현황에 우선순위를 두고 최신순으로 정렬

## 📝 리팩토링 상세 내용

- 사용자의 등록 전시회 목록을 등록 현황에 우선순위를 두고 최신순으로 정렬

## ✅ TODO

- [x] 사용자의 등록 전시회 목록을 등록 현황에 우선순위를 두고 최신순으로 정렬
