### ISSUE TITLE
🔨[Refactor] 3가지 알림 종류 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#291]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 3가지 알림 종류 변경

## 📝 리팩토링 상세 내용

[변경 전]
- 좋아요한 전시회 시작일 알림
- 좋아요한 전시회 마감일 알림
- 캘린더에 저장한 전시회 방문 날짜 알림

[변경 후]
- 좋아요한 전시회 시작일/마감일 알림
- 혼자 가는 전시회 날짜 알림
- 모임에서 가는 전시회 날짜 알림

## ✅ TODO

- [x] 3가지 알림 종류 변경
