### ISSUE TITLE
💡[Feature] 모임의 캘린더에 전시회 관람 일정 추가 기능 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#30]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 모임의 캘린더에 전시회 관람 일정 추가 기능 구현
## 📝 기능 상세 내용

- 모임의 캘린더에 전시회 관람 일정 추가 기능 구현

## ✅ TODO

- [x] 모임의 캘린더에 전시회 관람 일정 추가 기능 구현
- [ ] +사진 바이트 형식으로 전환
- [x] +전시회에 대한 별점 구현

**Comment by cofls980** [comment]
"사진 바이트 형식으로 전환"은 나중에 한 번에 해결 예정
