### ISSUE TITLE
💡[Feature] 내 기록 추가 기능 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#38]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 기록 추가 기능 구현

## 📝 기능 상세 내용

- 기록 추가 기능 구현

## ✅ TODO

- [x] 개인의 기록 추가 기능 구현
- [x] 개인이 속한 모임이 갔다온 전시회에 대한 기록 추가 기능 구현
