### ISSUE TITLE
🔨[Refactor] 기록 추가 기능 중 모임에서 작성한 자신의 기록 조회 방법 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#40]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 기록 추가 기능 중 모임에서 작성한 자신의 기록 조회 방법 변경

## 📝 리팩토링 상세 내용

- 기록 추가 기능 중 모임에서 작성한 자신의 기록 조회 방법 변경
- 모임 내에서 작성한 기록 중 사용자 자신의 기록인지에 대한 필터링이 부족하고, 검증을 짧게 만들 수 있을 것으로 생각

## ✅ TODO

- [x] 기록 추가 기능 중 모임에서 작성한 자신의 기록 조회 방법 변경
