### ISSUE TITLE
🔨[Refactor] 개발 중 userId 지정 방법을 코드 내부가 아닌 http header로 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#41]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 개발 중 userId 지정 방법을 코드 내부가 아닌 http header로 변경

## 📝 리팩토링 상세 내용

- 개발 중 코드 내부에서 각 service마다 userId를 지정할 수 있는 코드를 사용했는데
- 테스트 과정 중 여러 요청이 service마다 다른 userId로 인해 테스트 진행이 더뎌지는 것을 발견
- 따라서 userId 지정 방법을 service 코드 내부가 아닌 http 요청의 header에 넣어서 사용할 예정

## ✅ TODO

- [x] 개발 중 userId 지정 방법을 코드 내부가 아닌 http header로 변경
- [x] 기존 service에서 사용하는 userId를 http header의 값을 사용할 수 있도록 수정
