### ISSUE TITLE
💡[Feature] 한 전시회에 대한 내 기록 목록 조회 기능 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#44]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 한 전시회에 대한 기록 목록 조회 기능 구현

## 📝 기능 상세 내용

- 개인이 작성한 한 전시회에 대한 기록 목록 조회
    - 개인 일정에 대한 기록
    - 속한 모임에 대한 기록

## ✅ TODO

- [x] 개인이 작성한 한 전시회에 대한 기록 목록 조회
