### ISSUE TITLE
💡[Feature] 내 전시회의 기록 조회

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Backend#46]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 내 전시회의 기록 조회

## 📝 기능 상세 내용

- 내 전시회의 기록 조회

## ✅ TODO

- [x] 내 전시회의 기록 조회

**Comment by cofls980** [comment]
= 내 기록의 전시회 목록 조회
