### ISSUE TITLE
💡[Feature] 기록 수정 기능 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#48]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 기록 수정 기능 구현

## 📝 기능 상세 내용

- 기록 수정 기능 구현

## ✅ TODO

- [x] 기록 수정 기능 구현
