### ISSUE TITLE
💡[Feature] 내 기록의 한 전시회에 대하여 캘린더에 저장된 날짜 조회

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#52]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 내 기록의 한 전시회에 대하여 캘린더에 저장된 날짜 조회

## 📝 기능 상세 내용

- 내 기록의 한 전시회에 대하여 캘린더에 저장된 날짜 조회

## ✅ TODO

- [x] 내 기록의 한 전시회에 대하여 캘린더에 저장된 날짜 조회
