### ISSUE TITLE
💡[Feature] 전시 메이트가 갔다온 전시회 목록

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#54]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 전시 메이트가 갔다온 전시회 목록

## 📝 기능 상세 내용

- 전시 메이트가 갔다온 전시회 목록

## ✅ TODO

- [x] 전시 메이트가 갔다온 전시회 목록
