### ISSUE TITLE
🔨[Refactor] equals 사용 수정 및 디비 업데이트 데이터 비교 위치 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#55]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- equals 사용 수정 및 디비 업데이트 데이터 비교 위치 변경

## 📝 리팩토링 상세 내용

- equals 사용 수정 및 디비 업데이트 데이터 비교 위치 변경

## ✅ TODO

- [x] equals 사용 수정 및 디비 업데이트 데이터 비교 위치 변경
