### ISSUE TITLE
🔨[Refactor] 디비 변경이 있는 모든 로직에Transactional 어노테이션 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#59]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 디비 변경이 있는 모든 로직에Transactional 어노테이션 추가

## 📝 리팩토링 상세 내용

- 디비 변경이 있는 모든 로직에Transactional 어노테이션 추가

## ✅ TODO

- [x] 디비 변경이 있는 모든 로직에Transactional 어노테이션 추가
