### ISSUE TITLE
💡[Feature] 유저 더미 데이터

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#6]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 유저 더미 데이터 작성 및 생성

## 📝 기능 상세 내용

- 유저 더미 데이터 작성 및 생성

## ✅ TODO

- [x] 유저 더미 데이터 작성 및 생성
