### ISSUE TITLE
💡[Feature] 전시회 목록 조회(+전시회 검색)

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#61]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 전시회 목록 조회(+전시회 검색)

## 📝 기능 상세 내용

- 전시회 목록 조회(+전시회 검색)

## ✅ TODO

- [x] 전시회 목록 조회(+전시회 검색)
- [x] 전시회 좋아요 조회
