### ISSUE TITLE
💡[Feature] 내 기록의 전시회 방문 날짜 추가

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Backend#63]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 내 기록의 전시회 방문 날짜 추가

## 📝 기능 상세 내용

- 내 기록의 전시회 방문 날짜 추가

## ✅ TODO

- [x] 내 기록의 전시회 방문 날짜 추가
