### ISSUE TITLE
💡[Feature] 한 전시회에 대한 모임 기록 목록 조회 기능 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#65]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 한 전시회에 대한 모임 기록 목록 조회 기능 구현

## 📝 기능 상세 내용

- 한 전시회에 대한 모임 기록 목록 조회 기능 구현

## ✅ TODO

- [x] 한 전시회에 대한 모임 기록 목록 조회 기능 구현
