### ISSUE TITLE
💡[Feature] 전시 메이트의 전시회 기록 목록

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Backend#79]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 전시 메이트의 전시회 기록 목록

## 📝 기능 상세 내용

-전시 메이트의 전시회 기록 목록

## ✅ TODO

- [x] 전시 메이트의 전시회 기록 목록
