### ISSUE TITLE
💡[Feature] 좋아요 전시회 목록 조회

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Backend#85]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 좋아요 전시회 목록 조회

## 📝 기능 상세 내용

- 좋아요 전시회 목록 조회
- 
## ✅ TODO

- [ ]좋아요 전시회 목록 조회
