### ISSUE TITLE
💡[Feature] 전시회 좋아요 해제 클릭

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Backend#87]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 좋아요 전시회 삭제
- 
## 📝 기능 상세 내용

-  좋아요 전시회 삭제

## ✅ TODO

- [x]  좋아요 전시회 삭제
