### ISSUE TITLE
🔨[Refactor] 캘린더 일정을 일 별이 아닌 월 별로 응답 데이터로 주는 것으로 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Backend#96]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 캘린더 일정을 일 별이 아닌 월 별로 응답 데이터로 주는 것으로 변경

## 📝 리팩토링 상세 내용

- 캘린더 일정을 일 별이 아닌 월 별로 응답 데이터로 주는 것으로 변경

## ✅ TODO

- [x] 캘린더 일정을 일 별이 아닌 월 별로 응답 데이터로 주는 것으로 변경
